config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :rooms
  resources :bookings
  root to: 'pages#index'
  get '/all_rooms', to: 'pages#rooms'
  devise_for :users
  resources :users, :only => [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
<!-- DEVISE ALERT MESSAGE -->
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<!-- -->

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><h6><%= message %></h6></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer light-blue">
  <div class="container">
    <div class="row">
      <div class="col l8 s12">
        <h5 class="white-text">About us</h5>
        <p class="col l4 offset-s12 s12">David Regency Hotel is a perfect venue for a comfortable stay as well as business meetings, conferences and trainings.</p>
      </div>
      <div class="col l4 offset-s12 s12">
        <h5 class="white-text">Services</h5>
        <ul>
          <li><%= link_to "Home", root_path, :class => "grey-text text-lighten-3" %></li>
          <li><%= link_to "Rooms", all_rooms_path, :class => "grey-text text-lighten-3" %></li>
          <% if user_signed_in? %>
            <li><%= link_to "My Profile", current_user, :class => "grey-text text-lighten-3" %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path, :class => "grey-text text-lighten-3" %></li>
            <li><%= link_to "Logout", destroy_user_session_path, :class => "grey-text text-lighten-3" %></li>
          <% else %>
            <li><%= link_to "Login", new_session_path(:user), :class => "grey-text text-lighten-3" %></li>
            <li><%= link_to "Signup", new_user_registration_path, :class => "grey-text text-lighten-3" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright white">
    <div class="container black-text">
      © 2020 Online Hotel Booking Web App, All rights reserved
      <%= link_to "Some Link", "#", :class => "black-text right" %>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "My Account", current_user %></li>
  <li><%= link_to "Settings", edit_user_registration_path %></li>
  <li class="divider"></li>
  <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
</ul>
<nav>
  <div class="nav-wrapper light-blue">
    <%= link_to image_tag("hotel-logo.png", size: 64), root_path, :class => "hotel-logo" %>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Rooms", all_rooms_path %></li>
      <% if user_signed_in? %>
        <% if current_user.admin == true %>
          <li><%= link_to "Admin Dashboard", rails_admin.dashboard_url %></li>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
        <% else %>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Dropdown<i class="material-icons right">arrow_drop_down</i></a></li>
        <% end %>

      <% else %>
        <li><%= link_to "Log in", new_session_path(:user) %></li>
        <li><%= link_to "Signup", new_user_registration_path %></li>
      <% end %>
      <!-- Dropdown Trigger -->
    </ul>
  </div>
</nav>

<script type="text/javascript">
  $(".dropdown-trigger").dropdown();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>